<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="apc_suction_gripper">
  <xacro:macro name="apc_suction_gripper" params="side">

    <xacro:property name="tip_length" value="${0.0 + 0.0}" scope="local"/>
    <xacro:property name="suction_cup_z_offset" value="0.448" scope="local"/>
    <xacro:property name="suction_cup_z_collision_offset" value="0.0" scope="local"/>
    <xacro:property name="suction_cup_z_offset_90" value="0.374" scope="local"/>
    <xacro:property name="suction_cup_x_offset_90" value="0.050" scope="local"/>
    <xacro:property name="suction_cup_x_collision_offset_90" value="0.0" scope="local"/>
    <xacro:property name="gripper_collision_radius" value="0.02" scope="local"/>
    <xacro:property name="gripper_collision_90_length" value="0.04" scope="local"/>


    <!-- to change realsense joint location change the rpy and xyz below-->
    <!-- transform is located in apc_gripper_description/launch/gripper_static_tf.launch -->

    <!-- <xacro:property name="suction_cup_z_offset" value="0.375" scope="local"/> -->
    <!-- <xacro:property name="suction_cup_offset_half" value="0.18725" scope="local"/> -->

    <!-- Base of end effector -->
    <link name="${side}_gripper_base">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://apc_gripper_description/meshes/APC_Suction_Hand_2016.dae"/>
        </geometry>
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0.01 0.0 ${suction_cup_z_offset/2}"/>
        <geometry>
          <cylinder length="${suction_cup_z_offset}" radius="${gripper_collision_radius}" />
        </geometry>
        <material name="darkred">
          <color rgba=".5 .1 .1 1"/>
        </material>
      </collision>
      <collision>
      <!-- collision part for the realsense -->
          <origin rpy="0 0 0" xyz="-0.05 0.0 0.01"/>
        <geometry>
          <box size="0.1 0.15 0.03" />
        </geometry>
        <material name="darkred">
          <color rgba=".5 .1 .1 1"/>
        </material>
      </collision>
      <!-- collision part for the 90 degree suction cup -->
      <collision>
          <origin rpy="0 ${pi/2} 0" xyz="${suction_cup_x_offset_90/2.0} 0.0 ${suction_cup_z_offset_90}"/>
        <geometry>
          <cylinder length="${gripper_collision_90_length}" radius="0.02" />
        </geometry>
        <material name="darkred">
          <color rgba=".5 .1 .1 1"/>
        </material>
      </collision>
      <inertial>
        <origin rpy="0 ${pi} ${pi}" xyz="0.0 0.0 0.0"/>
        <mass value="0.5"/>
        <inertia ixx="2e-08" ixy="0" ixz="0" iyy="3e-08" iyz="0" izz="2e-08"/>
      </inertial>
    </link>

    <!-- Pneumatic Gripper Base Joint -->
    <joint name="${side}_gripper_base" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0.0"/>
      <parent link="${side}_hand"/>
      <child link="${side}_gripper_base"/>
    </joint>

    <!-- Pneumatic Gripper Tip joint          0 degree -->
    <!--  TODO juxi hacked this with clehnert.... -->
    <joint name="${side}_endpoint" type="fixed">
      <origin rpy="0 -1.57 0" xyz="0 0 ${suction_cup_z_offset+suction_cup_z_collision_offset}"/>
      <parent link="${side}_gripper_base"/>
      <child link="${side}_gripper"/>
    </joint>

    <!-- Pneumatic Gripper Tip link           0 degree-->
    <link name="${side}_gripper">
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="0.0001"/>
        <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0.0"/>
      </inertial>
    </link>

    <!-- Pneumatic Gripper Tip joint          90 degree -->
    <joint name="${side}_endpoint_90" type="fixed">
      <origin rpy="0 0 0" xyz="${suction_cup_x_offset_90+suction_cup_x_collision_offset_90} 0 ${suction_cup_z_offset_90}"/>
      <parent link="${side}_gripper_base"/>
      <child link="${side}_gripper_90"/>
    </joint>

    <!-- Pneumatic Gripper Tip link           90 degree-->
    <link name="${side}_gripper_90">
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="0.0001"/>
        <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0.0"/>
      </inertial>
    </link>


    <!-- Distance from Realsense RGB Camera to centre of Baxter (left/right)_hand -->
    <joint name="${side}_endpoint_realsense" type="fixed">
      <origin rpy="0.0 -1.85 0.0" xyz="-0.09 0.00 0.02"/>
      <parent link="${side}_hand"/>
      <child link="${side}_realsense"/>
    </joint>

    <!-- Realsense Tip link -->
    <link name="${side}_realsense">
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="0.0001"/>
        <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0.0"/>
      </inertial>
    </link>

  </xacro:macro>
</robot>
